### ISSUE TITLE
Update User Creation directions

### ISSUE THREAD

**Issue by akradin** [ga-wdi-boston/aws-s3-setup-guide#12]
It appears as though AWS has ran an update causing steps two through five to be incorrect. It is still easy to figure out what to do, the button titles are just labeled differently

**Comment by BenGitsCode** [comment]
@akradin could you provide some details on the different labels, just so we can note the changes to be made to the repository? I'll go through this again to to make changes.  Thanks for posting this!

**Comment by akradin** [comment]
Yup! So I think the instructions should look like this 
1. Select Users in the left sidebar.
2. Click `Add User` near the top of the page.
3. Enter wdi-upload into the text box.
4. Under access type, click Programmatic Access
6. Click Next
7. Highlight Add User to Group
8. Click Next
9. Click create User

**Comment by BenGitsCode** [comment]
Awesome! You da man 👍
