### ISSUE TITLE
Amazon updated, US Standard no longer exists as a region

### ISSUE THREAD

**Issue by laurpaik-zz** [ga-wdi-boston/aws-s3-setup-guide#17]
<img width="267" alt="screen shot 2017-03-02 at 5 26 54 pm" src="https://cloud.githubusercontent.com/assets/23316584/23534026/38e903ec-ff83-11e6-9522-0f640955ce9e.png">

^ this was what I saw for my region options when creating a bucket. I went with Northern Virginia, but yea US Standard is no longer an option.

**Comment by BenGitsCode** [comment]
Notable that Lauren is seeing a completely different UI than everyone else in 016.

**Comment by BenGitsCode** [comment]
I've tried this in 3 browsers now and still get the same UI. Can I work with you at some point tomorrow to try and pin down why yours is different/who else is having that issue?

[![https://gyazo.com/646fc479b94ac3328349ca4030b71e14](https://i.gyazo.com/646fc479b94ac3328349ca4030b71e14.png)](https://gyazo.com/646fc479b94ac3328349ca4030b71e14)

**Comment by laurpaik-zz** [comment]
@BenGitsCode yea, that sounds good. I'm usually in by 8 if you want to look at it then.

**Comment by jrhorn424** [comment]
It was my understanding that US Standard is a newer region than N. Virginia, and superseded it in the API.

**Comment by BenGitsCode** [comment]
So I just texted with with Lauren. 

There was an option on her machine to switch to the `old console` but I can't replicate the new one on mine. 

She successfully created her IAM user and S3 bucket using the instructions in this update https://github.com/ga-wdi-boston/aws-s3-setup-guide/tree/016/iam-update

Her only U.S. choice was `U.S. East`, with subsets (i.e. north viriginia) but when she clicked `switch to old console` that same bucket showed `US Standard` as its region.

**Comment by jrhorn424** [comment]
Is this resolved?

**Comment by BenGitsCode** [comment]
Yes. I'm still not sure why the region shows differently in the old vs new console. But switching to the old console showed the correct region.

This issue is resolved to my satisfaction as long as @laurpaik agrees

**Comment by laurpaik-zz** [comment]
I agree.
