### ISSUE TITLE
Error in Bucket Policy Editor window

### ISSUE THREAD

**Issue by JaimeGaribaldo7** [ga-wdi-boston/aws-s3-setup-guide#6]
After generating the JSON policy object I tried to paste it into the bucket policy editor window and it gives me an error that says:

Invalid principal in policy - "AWS" : "arn:aws:iam::278492089080:user/wdi-up"

I dont know if this might help, but it says wdi-up instead of upload. I remember typing "upload", maybe I'm tired and didn't type the full thing, but maybe that will help.

**Comment by JaimeGaribaldo7** [comment]
This is what my JSON bucket policy looks like:

``` json
{
  "Id": "Policy1476322535997",
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "Stmt1476322517625",
      "Action": [
        "s3:PutObject",
        "s3:PutObjectAcl"
      ],
      "Effect": "Allow",
      "Resource": "arn:aws:s3:::pallettown/*",
      "Principal": {
        "AWS": [
          "arn:aws:iam::278492089080:user/wdi-up"
        ]
      }
    }
  ]
}
```

**Comment by jrhorn424** [comment]
I formatted your paste. Please do that in the future.

Compare your paste with the relevant parts of my bucket policy.

``` json
{
    "Version": "2012-10-17",
    "Id": "Policy1467979886129",
    "Statement": [
        {
            "Sid": "Stmt1467979861784",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::956077816057:user/wdi-upload"
            },
            "Action": [
                "s3:PutObject",
                "s3:PutObjectAcl"
            ],
            "Resource": "arn:aws:s3:::ga-wdi-boston-jeffh/*"
        }
    ]
}
```

**Comment by JaimeGaribaldo7** [comment]
Just to be clear, I'm allowed to make adustents directly on the editor window, right?

**Comment by gaand** [comment]
It's just JSON, so if you don't invalidate the format, yes.

**Comment by JaimeGaribaldo7** [comment]
I deleted my comment. Now that I think about it, that was a bad idea. For anyone wondering what @gaand was responding to. I asked: "Just to be clear, I'm allowed to make changes in the editor window, right?"

**Comment by JaimeGaribaldo7** [comment]
I found my problem, When I copied the Amazon Resource Name(ARN), I didn't copy the entire link. It was cut off where I mentioned earlier. It should be `wdi-upload` and NOT `wdi-up`. It seems to have worked.
