### ISSUE TITLE
No Save button in policy generator modal

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/aws-s3-setup-guide#8]
I pasted the JSON, but I see no save option in the modal!

**Comment by jrhorn424** [comment]
Which save button do you mean? This is the process I used and it worked for me.

<img width="666" alt="s3_management_console" src="https://cloud.githubusercontent.com/assets/388761/19351568/556291ea-912a-11e6-984b-029e41a94e04.png">

<img width="652" alt="s3_management_console" src="https://cloud.githubusercontent.com/assets/388761/19351588/650d3bc2-912a-11e6-8c63-b87dedba1e75.png">

<img width="675" alt="s3_management_console" src="https://cloud.githubusercontent.com/assets/388761/19351605/75918d86-912a-11e6-9c0a-16b487991b83.png">

**Comment by julie1013** [comment]
This is where I'm stuck. I showed it to Chris and he's not sure what's wrong either. I don't see any bucket policy modal... unless that's what the screenshot shows that I'm in. If that is the case, I can't see the save button.

![screen shot 2016-10-13 at 9 51 36 am](https://cloud.githubusercontent.com/assets/14143334/19351671/af36c4d4-912a-11e6-9c0f-63c130d69b1c.png)
![screen shot 2016-10-13 at 9 51 43 am](https://cloud.githubusercontent.com/assets/14143334/19351672/af398476-912a-11e6-9bcd-84b498763fbe.png)

**Comment by jrhorn424** [comment]
Did you read the instructions in that dialog box?

**Comment by julie1013** [comment]
Yeah, I copied the text.

**Comment by jrhorn424** [comment]
The directions in the README should get you there after you've copied the text.

**Comment by jrhorn424** [comment]
You clicked close? You created the bucket? You clicked properties on the bucket window? It's all there.

**Comment by julie1013** [comment]
Yep, yep, and yep. I had to click properties on the right side of the S3 tab to get what I needed.
