### ISSUE TITLE
Add explicit text to NOT COMMIT SECRETS

### ISSUE THREAD

**Issue by berziiii** [ga-wdi-boston/aws-s3-setup-guide#9]
Even though credentials are ignored, suggestion from @jrhorn424

**Comment by gaand** [comment]
Is this insufficient?

> Note well: credentials.csv contains secrets! Do not share them or store them in git. The .gitignore in this repository explicitly ignores this file.

**Comment by BenGitsCode** [comment]
My vote is no it is not. We have mentioned this and emphasized its importance on numerous occasions. Will close this after my PR is merged without objections.

 @jrhorn424 I'd like to discuss finer details of the preferred language we use both with the above snippet as well as some information related to both #7 and #4 this week if you're able.

**Comment by gaand** [comment]
Objection.
